[package]
name = "kairoi-web"
version = "0.1.0"
edition = "2021"

[features]
debugging = ["game_lib/debugging"]

[dependencies]
game_lib = { package = "kairoi", path = "../../" }
bevy = { workspace = true }